services:
  web:
    image: nginx:latest
    volumes:
      - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/backend
      - ./frontend/dist:/var/www/frontend
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - php-fpm
      - db
      - frontend
    networks:
      - app-network

  php-fpm:
    build: docker
    restart: always
    volumes:
      - ./backend:/var/www/backend
      - ./docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    env_file:
      - .env
    networks:
      - app-network

  db:
    image: postgres:10.1
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 54322:${DB_PORT}
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - php-fpm
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
